"""empty message

Revision ID: 7163a298ee9c
Revises: 12e2f4b7a02a
Create Date: 2023-05-25 17:18:12.537534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7163a298ee9c'
down_revision = '12e2f4b7a02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
